name: 'Validate PR title'

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  conventional-pr-title:
    name: Conventional commit
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}
